spring.application.name=ballistics_backend
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB:ballistics_db}
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD:password123}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=true
app.s3.bucket=renders-dev-304896960484-us-west-1-an
app.tmp.dir = .tmp
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}